### ISSUE TITLE
🐞Bug: App not starting from 'air'

### ISSUE THREAD

**Issue by alldo-dev** [atridadl/goth.stack#1]
# Expected Behavior
After following the [instructions](https://github.com/atridadl/goth.stack?tab=readme-ov-file#instructions) to get the app running, the app should start normally

# Current Behavior
When running the 'air' command the app returns an error as follows:
![image](https://github.com/atridadl/goth.stack/assets/158750632/460c05a6-ef8b-4a4e-878b-cc39de1fc755)

> '.' is not recognized as an internal or external command,
> operable program or batch file.
> failed to build, error: exit status 1
> running...
> CMD will not recognize non .exe file for execution, path: <path-to-app>\goth.stack\tmp\main > -ip 127.0.0.1 -port 3000

# Possible Solution
there's a typo in the `.air.toml` file where under [build] > cmd the instruction is written like
```
cmd = "go build -o ./tmp/main . & cd lib/stylegen && ./gen.sh"
                              ^
```
needs to be corrected so that it shows the following
```
cmd = "go build -o ./tmp/main.exe & cd lib/stylegen && ./gen.sh"
                             ^
```

# Steps to Reproduce
Follow the [instructions](https://github.com/atridadl/goth.stack?tab=readme-ov-file#instructions) 

# Context (Environment)
tryied on VS Code in windows 11

**Comment by alldo-dev** [comment]
[PR#2](https://github.com/atridadl/goth.stack/pull/2) deals with the issue

**Comment by atridadl** [comment]
Taking a look.

**Comment by atridadl** [comment]
Are you running this in windows via command prompt or powershell? @alldo-dev 

This script assumes a UNIX shell, and is valid there. Tested on macOS and Linux (Debian). Therefore I'm not fond of the .exe fix. I will come up with something for different architectures. Also, I should add that this repo is now a mirror of https://codeberg.org/atridad/goth.stack, so I will be doing that work there.

**Comment by atridadl** [comment]
I'm going to remove this one and add a note to use WSL if on windows.

**Comment by alldo-dev** [comment]
Understood! Thanks for your feedback
